var GAME_LEVELS = [
  ["                                                                    ",
   "                                                                    ",
   "                                                                    ",
   "                                                                    ",
   "         o                                                          ",
   "   xx   xx      o            o     xx   xx                          ",
   "    x   x       x     xx     x      x   x                           ",
   "    x   x                           x   x                           ",
   "    x  xx                           x   x                           ",
   "    x   x                           x  xx                           ",
   "   xx   xx                          xooox                           ",
   "  x       x                         xooox                           ",
   " x   x     x                        xooox                           ",
   " x    @    x                  o      xxx         o          y       ",
   " x         x                                              xxxxx     ",
   "  x       x                                                xxx      ",
   "   x+++++x    x                                            xxx      ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxwwwwwxxxxxxxxxxxxxx!!!!!xxxx+++xxx+++x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  "],
  ["                                                                                            ww               ",
   "    @                                                                                       ww               ",
   "                                                                                            ww               ",
   "  xxxxx                                                                                     ww               ",
   "   xxx                                                                x   x  ooo            ww               ",
   "   xxx                                                                x   x  ooo   xxxxx    ww       y       ",
   "+++xxx++++++                                                          x!!!x  ooo   xxxxx    ww               ",
   "xxxxxxxxxxxx                                  xx   oo   xx       xxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx                                    xxxxxxxxxxxx                                  xxxxxxxxxxxxxxxxx",
   "xxxxxxxxxx                                    xx  x  x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                                    xx  x  x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                                   xxx  x  x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                                    xx  x  x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                                    xx  x  x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                                    xx  x  x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                            xxxxxxxxxx  xxxxxxxx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                            xxo xx  xx  xx x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                                xx  xx  x  x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                      xx        xx  xx  x  x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                                xx  xx  x  x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                              o xx  xx  x  x  xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                           xxxxxxxxxxxxxxxxxxxxx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx                           xxxxxxxxxxxxxxxxxxxxx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxx  xx      xx          xx   xx      xx    xx   xx                                    xxxxxxxxxxxxxxx",
   "        xx   x      x                xx      xx    xx   xx                                    xxxxxxxxxxxxxxx",
   "        xx   x     xx                xx      xx    xx   xx                                    xxxxxxxxxxxxxxx",
   "        xx   x     ox                xx      xx    xx   xx                                    xxxxxxxxxxxxxxx",
   "        xx   xoo  oox              xxxx      xx  xxxx   xx                                    xxxxxxxxxxxxxxx",
   "        xx   x++++++x              xxxx      xx  xxxx   xx                                    xxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                    xxxxxxxxxxxxxxx"],
  ["                                                                                    ",
   "   @                                                                                ",
   "                                                        xxxxxxxxxx                  ",
   "xxxxxxxxxxx                                             xxxxxxxxxx                  ",
   "xxxxxxxxxxx                                             xx      xx                  ",
   "xxxxxxxxx                                         xx            xx                  ",
   "xxxxxxxxx                                         xx            xx                  ",
   "xxxxxxxxx      xx                                  xxx        xxx                   ",
   "xxxxxxxxxoo    xx                      xxxxxxxxxx    xxxwwwwwxx                     ",
   "xxxxxxxxxooo   xxo                    xxxxxxxxxxx      xxwwxx                       ",
   "xxxxxxxxxxxxxxxxx                      xxxxxxxxxx      xxwwxx                       ",
   "xxxxxxxxxxxxxxxxx                      xxxxxxxxxx      xxwwxx                       ",
   "xxxxxxxxx                              xxxxxxxxxx      xxwwxx                       ",
   "xxxxxxxxx            xx        xxxxx         xxx       xxwwxx                       ",
   "xxxxxxxxxoo          xx       xxxx           xxx       xxwwxx                       ",
   "xxxxxxxxxoooooo      xxo       xxx           xxx       xxwwxx                       ",
   "xxxxxxxxxxxxxxxxxxxxxxx          xxxwwwwwwwwwxx        xxwwxx                       ",
   "xxxxxxxxxxxxxxxxxxxxxxx            xxxwwwwwxxx         xxwwxx                       ",
   "xxxxxxxxx                    x       xxwwwwxx          xxwwxx                       ",
   "xxxxxxxxx                            xxwwwwxx          xxwwxx                       ",
   "       xx                           xxxwwwwxx          xxwwxx                       ",
   "       xx                          xxxxwwwwxxxx        xxwwxx                       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxx   x                       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxx   x                       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxx   x                       ",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    xxxxxxx  ooooooooooox                       ",
   "xx                                 x    xxxxxxx  ooooooooooox                       ",
   "xx                                 x    xxxxxxxwwxxxxxxxxxxxx                       ",
   "xx                                      xxxxxxx  xxxxxxxxxxxx                       ",
   "xx                                      xxxxxxx  xxxxxxxxxxxx                       ",
   "xx                                      xxxxxxx  xxxxxxxxxxxx                       ",
   "xx                       xxx             xxxxxx  xxxxxxxxxxxx                       ",
   "xx                        xxx                    xxxxxxxxxxxx                       ",
   "xx     xx      xx      xx  xxx                   xxxxxxxxxxxx                       ",
   "xx                          xxx                xxxxx     xxxx  xx                   ",
   "xx       xx!!!!!!!!!!!!!!!!xxxxx!!!!xxxxxxxxxxx            xxxxxx                   ",
   "xx       xx                                                                         ",
   "         xx                                                                         ",
   "         xx                                                                         ",
   "o        xx                                          xx                             ",
   "o        xx         xx                       xx            xxxxx+                   ",
   "xx       xx         xx                xx                   xx  xx                   ",
   "xx                  xx          xx                         xx                       ",
   "xx             xx   xx   xx                                xx                       ",
   "xx             xx   xx   xx                                xx          y            ",
   "xx             xx   xx   xx                                xx                       ",
   "xxxxxxxxxxxxxxxxx   xx   xx++++++++++++++++++++++++++++++++xxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                       @                                                                                      ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                   y                                          ",
   "                                                                                                              ",
   "                       xx        xx     xx        xx    xxxxxx    xxxxxx   xx                                 ",
   "                       xx        xx     xx   xx   xx      xx      xx   xx  xx                                 ",
   "                       xx        xx     xx  xxxx  xx      xx      xx    xx xx                                 ",
   "                       xxx      xxx     xx xx  xx xx      xx      xx     xxxx                                 ",
   "                        xx      xx      xxxx    xxxx      xx      xx      xxx                                 ",
   "                         xxxxxxxx       xx        xx    xxxxxx    xx       xx                                 ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
